version: '3.9'

services:
  db:
    image: postgres:15
    container_name: crewai_db
    env_file:
      - .env
    environment:
      POSTGRES_USER: crewai_user
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: crewai
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  # The Streamlit app
  web:
    build: .
    container_name: crewai_studio
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - DB_URL=postgresql://crewai_user:secret@db:5432/crewai
    ports:
      - "8501:8501"
